### ISSUE TITLE
Code implementation

### ISSUE THREAD

**Issue by sujanme25** [giarcieri/Uncertainty-estimation-with-Probabilistic-and-Bayesian-Neural-Networks#1]
Thank you for the code.
I have data as (X_train.shape, y_train.shape, X_test.shape,y_test.shape= ((23376, 4), (23376,), (5844, 4), (5844,))), how to implement this code?
When i try to do the preds_mdn = nn_mdn(X_test).sample(runs), the error come up as "'tuple' object has no attribute 'rank'".

**Comment by giarcieri** [comment]
> Thank you for the code. I have data as (X_train.shape, y_train.shape, X_test.shape,y_test.shape= ((23376, 4), (23376,), (5844, 4), (5844,))), how to implement this code? When i try to do the preds_mdn = nn_mdn(X_test).sample(runs), the error come up as "'tuple' object has no attribute 'rank'".

Hi! Did you modify the input shape of the NN accordingly? If yes, I am not sure about the source of the error without looking at the code, but you can modify that line into:
preds_mdn = np.asarray([nn_mdn.predict(X_test) for _ in range(runs)])
which should work.

**Comment by sujanme25** [comment]
Thank you that works but one thing now i am getting only 100 sigma and mean when i set for runs =100. so do i need to run it 5844 times to get 5844 means and sigma; since my test size is 5844.

**Comment by giarcieri** [comment]
If test size is 5844, then predictions with runs=100 have shape (100, 5844), which means 100 samples from the likelihood distribution (in this case, mixture of Gaussian) for each test data point. Taking the mean and std along axis 0 will provide you with 5844 means and sigma.

**Comment by giarcieri** [comment]
> Thank you that works but one thing now i am getting only 100 sigma and mean when i set for runs =100. so do i need to run it 5844 times to get 5844 means and sigma; since my test size is 5844.

If test size is 5844, then predictions with runs=100 have shape (100, 5844), which means 100 samples from the likelihood distribution (in this case, mixture of Gaussian) for each test data point. Taking the mean and std along axis 0 will provide you with 5844 means and sigma.

**Comment by sujanme25** [comment]
Thank you

**Comment by sujanme25** [comment]
'History' object is not subscriptable error was coming when trying ens_bnn

**Comment by sujanme25** [comment]
TypeError                                 Traceback (most recent call last)
<ipython-input-77-4fc64a025ea5> in <module>
----> 1 NNs_hist_train=ensbnn_dropout.train(X_train, y_train, epochs=20, batch_size=50,validation_data=(X_test,y_test))

<ipython-input-68-efe3684a2d26> in train(self, X_train, y_train, batch_size, epochs, validation_data)
    281                       verbose=2,
    282                       validation_data = validation_data)
--> 283             NNs_hist_train.append(hist['history'])
    284         return NNs_hist_train
    285 

TypeError: 'History' object is not subscriptable

**Comment by giarcieri** [comment]
Indeed the code does not support ens_bnn as it is not used in the notebook. If you want to use it, of course you have to adapt the code. Close it.

**Comment by sujanme25** [comment]
Thank You, How to find the optimized drop_out probability in concrete dropout?

**Comment by sujanme25** [comment]
Below error comes up when implementing code. 
WARNING:tensorflow:Gradients do not exist for variables ['concrete_dropout/p_logit:0', 'concrete_dropout_1/p_logit:0', 'concrete_dropout_2/p_logit:0', 'concrete_dropout_3/p_logit:0', 'concrete_dropout_4/p_logit:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss`argument?
WARNING:tensorflow:Gradients do not exist for variables ['concrete_dropout/p_logit:0', 'concrete_dropout_1/p_logit:0', 'concrete_dropout_2/p_logit:0', 'concrete_dropout_3/p_logit:0', 'concrete_dropout_4/p_logit:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss`argument?
